language: python
python:
  - "3.9.0"  # you can specify other python versions if needed

install:
  - pip install -r requirements.txt
  - pip install black
  - pip install flake8
  - pip install coverage
  - pip install coveralls

script:
  - black .
  - flake8
  - coverage run manage.py test  # assuming you have Django tests

after_success:
  - coveralls

dist: bionic

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"  # for example: "us-west-2"
  app: "django-tutorial"
  env: "django-env"
  bucket_name: "elasticbeanstalk-us-west-2-669592337256"
  bucket_path: "django-tutorial"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY

notifications:
  email:
    on_success: change
    on_failure: always

